### ISSUE TITLE
rJava error

### ISSUE THREAD

**Issue by joefisher** [christophergandrud/repmis#15]
Tried to install "repmis" on Win 64 Enterprise with R 3.1.2 64 bit. All software is up to date. 

> library(repmis)
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dirname(this$RuntimeLib)
  error: a character vector argument expected
Error: package or namespace load failed for ‘repmis’
> library(rJava)
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dirname(this$RuntimeLib)
  error: a character vector argument expected
Error: package or namespace load failed for ‘rJava’
>

**Comment by christophergandrud** [comment]
repmis now (v0.4.2) no requires rJava, unless you want to load Excel files.
