### ISSUE TITLE
Remove the rJava dependency if not xlsx is explicitly called

### ISSUE THREAD

**Issue by MansMeg** [christophergandrud/repmis#16]
I've been having huge problems with my students in the R programming class Im teaching that uses repmis from a Windows version.

You first has to choose where to temporarily download the files (Y/n choice) and rJava is used. In most cases you don't need to use the xlsx file. Would it be possible to move it to "suggests" and load this package into R if xlsx is used. 

/Måns

**Comment by christophergandrud** [comment]
That's a good idea. 

I just implemented it at 1fe302e2c896ef36c37f61953dfd2381883c6265. If you get a chance, please poke at it. I'll get the update on CRAN shortly.

**Comment by christophergandrud** [comment]
The new version (0.4.2) is on CRAN now.

**Comment by MansMeg** [comment]
Yay!
