### ISSUE TITLE
Package fails to install in R 3.0.2

### ISSUE THREAD

**Issue by moorepants** [christophergandrud/repmis#18]
I found this package because I want to be able to install R package versions that are compatible with the R provided in Ubuntu 14.04 LTS. But even installing this package fails because `install.packages('repmis')` tries to install the latest dependencies and they are not compatible with R 3.0.2. It'd be nice if the package that tries to solve the old package support could actually be installed in older versions of R. This is just a note, I think the problem is endemic to the R packaging eco-system.

**Comment by christophergandrud** [comment]
Thanks for the suggestion. Right now I think this is, as you say, a fundamental problem with R and a lot more work is needed.
